export type AuthLanguage = 'ar' | 'en' | 'tr';

export const authCopy = {
  ar: {
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    code: 'رمز التحقق',
    newPassword: 'كلمة المرور الجديدة',
    submit: 'متابعة',
    forgot: 'هل نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    verifyTitle: 'تحقق من بريدك الإلكتروني',
    verifyDescription: 'أدخل الرمز المكون من ستة أرقام المرسل إلى بريدك.',
    forgotTitle: 'استعادة كلمة المرور',
    resetTitle: 'تعيين كلمة مرور جديدة',
    registerTitle: 'ابدأ رحلتك الدراسية',
    loginTitle: 'مرحباً بعودتك',
    consent: 'أوافق على التواصل معي بخصوص طلب القبول.',
    consentRequired: 'يرجى الموافقة على التواصل قبل إنشاء الحساب.',
    resend: 'إعادة إرسال الرمز',
    success: 'تم بنجاح. يمكنك المتابعة الآن.',
    back: 'العودة للرئيسية',
    error: 'تعذر إكمال الطلب.',
  },
  en: {
    signIn: 'Sign in',
    signUp: 'Create account',
    email: 'Email address',
    password: 'Password',
    fullName: 'Full name',
    code: 'Verification code',
    newPassword: 'New password',
    submit: 'Continue',
    forgot: 'Forgot your password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    verifyTitle: 'Verify your email',
    verifyDescription: 'Enter the six-digit code sent to your email.',
    forgotTitle: 'Reset your password',
    resetTitle: 'Choose a new password',
    registerTitle: 'Start your journey',
    loginTitle: 'Welcome back',
    consent: 'I agree to be contacted about my admission request.',
    consentRequired: 'Please agree to be contacted before creating an account.',
    resend: 'Send code again',
    success: 'Completed successfully. You can continue now.',
    back: 'Back home',
    error: 'Unable to complete the request.',
  },
  tr: {
    signIn: 'Giriş yap',
    signUp: 'Hesap oluştur',
    email: 'E-posta adresi',
    password: 'Şifre',
    fullName: 'Ad soyad',
    code: 'Doğrulama kodu',
    newPassword: 'Yeni şifre',
    submit: 'Devam et',
    forgot: 'Şifrenizi mi unuttunuz?',
    noAccount: 'Hesabınız yok mu?',
    haveAccount: 'Zaten hesabınız var mı?',
    verifyTitle: 'E-postanızı doğrulayın',
    verifyDescription: 'E-postanıza gönderilen altı haneli kodu girin.',
    forgotTitle: 'Şifrenizi sıfırlayın',
    resetTitle: 'Yeni bir şifre seçin',
    registerTitle: 'Yolculuğunuzu başlatın',
    loginTitle: 'Tekrar hoş geldiniz',
    consent: 'Başvurum hakkında benimle iletişime geçilmesini kabul ediyorum.',
    consentRequired: 'Hesap oluşturmadan önce iletişim iznini kabul edin.',
    resend: 'Kodu tekrar gönder',
    success: 'Başarıyla tamamlandı. Şimdi devam edebilirsiniz.',
    back: 'Ana sayfaya dön',
    error: 'İstek tamamlanamadı.',
  },
} as const;

export function languageFromQuery(value: string | null): AuthLanguage {
  return value === 'ar' || value === 'tr' ? value : 'en';
}
